# **Python/ML workshop**
## **Organized by IET MPSTME**

## **Instructor**: Radhika Chapaneri

## Dec 2020

# **NumPy**
* Numpy stands for numerical python
* Fundamental package for numerical computations in Python
- NumPy arrays are **multi-dimensional** and most **engineering** python libraries use them instead. 


- They store the **same type of data** in each element and **cannot change size**.


**Motivation for NumPy**:
- Provide a uniform interface for handling numerical structured data
- Collect, store, and manipulate numerical data efficiently
- Low-cost abstractions
- Universal glue for numerical information, used in lots of external libraries such as TensorFlow, Keras, Scikit-Learn, etc.!

**Using Numpy we can perform**
* Mathematical and logical operations on arrays
* Fourier transforms
* Linear algebra operations
* Random number generation

In [1]:
import numpy as np

In [2]:
# Vector of all 0's
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [5]:
# Matrix of all 0's
x = np.zeros( (5,2) )
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(5, 2)


In [7]:
# 4 x 6 array of all 1's
y = np.ones( (4,6) )
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [8]:
# 3 x 2 array, all elements having same value
c = np.full( (3,2), 8)
print(c)

[[8 8]
 [8 8]
 [8 8]]


In [9]:
# Identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Matrix of random numbers
e = np.random.random( (4, 3))
print(e)

[[0.43965804 0.84741881 0.33553545]
 [0.59529261 0.17626527 0.79705149]
 [0.07306779 0.17751047 0.23276829]
 [0.2498833  0.40636497 0.45817049]]


* numpy.arange returns equally spaced numbers with in the
given range based on step 
* numpy.linspace returns equally spaced numbers within the
given range based on the sample number

In [11]:
# Arange v/s Linspace
print( np.arange(3, 10) )       # Does not include end point
print(np.arange(3, 10, 2))
print( np.linspace(0, 1, 25) )  # Includes end point

[3 4 5 6 7 8 9]
[3 5 7 9]
[0.         0.04166667 0.08333333 0.125      0.16666667 0.20833333
 0.25       0.29166667 0.33333333 0.375      0.41666667 0.45833333
 0.5        0.54166667 0.58333333 0.625      0.66666667 0.70833333
 0.75       0.79166667 0.83333333 0.875      0.91666667 0.95833333
 1.        ]


In [12]:
# Logspace
print( np.logspace(0, 1, 25) ) 

[ 1.          1.10069417  1.21152766  1.33352143  1.46779927  1.6155981
  1.77827941  1.95734178  2.15443469  2.37137371  2.61015722  2.87298483
  3.16227766  3.48070059  3.83118685  4.21696503  4.64158883  5.10896977
  5.62341325  6.18965819  6.81292069  7.49894209  8.25404185  9.08517576
 10.        ]


## **NumPy Slicing**

Numpy slicing image

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [15]:
# Slicing rows and columns
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [16]:
# Conditional slicing
a = np.array([[10, 20], [30, 40], [50, 60]])
idx = (a > 30)
print(idx)
print(a[idx])

# Equivalent
print(a[a > 30])

[[False False]
 [False  True]
 [ True  True]]
[40 50 60]
[40 50 60]


## **Math operations**

In [17]:
# Trivial math
x = np.array( [[50.0, 60.0], [70.0, 80.0]] )
y = np.array( [[10.0, 20.0], [30.0, 40.0]] )

print( np.add(x, y) )
print( np.subtract(x, y))
print( np.multiply(x, y) ) #this is element wise multiplication
print( np.divide(x, y) )

[[ 60.  80.]
 [100. 120.]]
[[40. 40.]
 [40. 40.]]
[[ 500. 1200.]
 [2100. 3200.]]
[[5.         3.        ]
 [2.33333333 2.        ]]


In [18]:
# Element-wise sqrt of matrix 
print( np.sqrt(x))

[[7.07106781 7.74596669]
 [8.36660027 8.94427191]]


In [19]:
# Dot product
v = np.array([9.0, 10.0])
w = np.array([11.0, 12.0])

print( np.dot(v, w) ) #Matrix multiplication 

219.0


In [20]:
# Dot product of matrices
print(x)
print(y)
print( np.dot(x, y) ) 

[[50. 60.]
 [70. 80.]]
[[10. 20.]
 [30. 40.]]
[[2300. 3400.]
 [3100. 4600.]]


In [21]:
# Sum along row or column
print(x)
print( 'Sum along columns:', np.sum(x, axis = 0) )
print( 'Sum along rows:', np.sum(x, axis = 1) )

[[50. 60.]
 [70. 80.]]
Sum along columns: [120. 140.]
Sum along rows: [110. 150.]


In [22]:
# Average along row or column
print(x)
print( 'Mean along columns:', np.mean(x, axis = 0) )
print( 'Mean along rows:', np.mean(x, axis = 1) )

[[50. 60.]
 [70. 80.]]
Mean along columns: [60. 70.]
Mean along rows: [55. 75.]


In [23]:
# Matrix transpose
print(x)
print( x.T )

[[50. 60.]
 [70. 80.]]
[[50. 70.]
 [60. 80.]]


In [24]:
# Matrix reshaping
a = np.arange(40).reshape(5, 8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [25]:
# All rows and 4th column
print( a[:, 3] )

[ 3 11 19 27 35]


In [26]:
# What's happening here?
print( a[1::2, ::3] )

[[ 8 11 14]
 [24 27 30]]


In [27]:
# And here?
print( a[-3:, -3:])

[[21 22 23]
 [29 30 31]
 [37 38 39]]


## **More than 2D**

In [28]:
# Reshaping a 3D tensor
a = np.arange(24).reshape(2, 3, 4)
print( a )

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [29]:
# Tensor slicing - 0
print( a[0, :, :] )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# Tensor slicing - 1
print( a[:, 0, :] )

[[ 0  1  2  3]
 [12 13 14 15]]


In [31]:
# Tensor slicing - 2
print( a[:, :, 0] )

[[ 0  4  8]
 [12 16 20]]


## **Code Vectorization**

In [33]:
#it is a technique  to implement arrays WITHOUT using loops
# Apply cos on each element of the list
from math import pi
x = np.linspace(-pi, pi, 4)
print( np.cos(x) )

[-1.   0.5  0.5 -1. ]


In [35]:
# Apply sqrt on each element of the list
z = [i**2 for i in range(1, 11)]
print(z)
print( np.sqrt(z) )

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


## **Numpy Broadcasting**

- The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.

In [36]:
a = np.array([[0.0,0.0,0.0], [10.0,10.0,10.0], 
              [20.0,20.0,20.0], [30.0,30.0,30.0]]) 
b = np.array([0.0, 1.0, 2.0])  
   
print('First array:')
print(a)

print('Second array:')
print(b)

print('First Array + Second Array')
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[0. 1. 2.]
First Array + Second Array
[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


## **NumPy Speed**

- Why people love NumPy?

In [37]:
%%timeit xvals = range(1000000)
[xval**2 for xval in xvals]

1 loop, best of 3: 294 ms per loop


In [38]:
%%timeit a = np.arange(1000000)
a**2

1000 loops, best of 3: 1.46 ms per loop


In [40]:
import math

In [41]:
%%timeit xvals = range(1000000)
[math.sin(xval) for xval in xvals]

10 loops, best of 3: 176 ms per loop


In [52]:
%%timeit a = np.arange(100000)
a**2

10000 loops, best of 3: 177 µs per loop


## **Stacking ndarrays**

- Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones

In [42]:
a = np.array( [[1, 2], [3, 4]] )

# Repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [43]:
# Tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [44]:
b = np.array([[5, 6]])

# Concatenate along rows
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
# Vertical stacking (aka vertical concatenate)
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# Concatenate along columns
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [47]:
# Horizontal stacking (aka horizontal concatenate)
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## **NumPy Exercises**

**1. Create a null vector of size 10 but the fifth value is 1.**

In [ ]:
None

**2. Create a 3x3 matrix with values ranging from 0 to 8.**

In [ ]:
None

**3. Find indices of non-zero elements from [1,2,0,0,4,0]. Hint: Use np.nonzero**

In [ ]:
None

**4. Create a 2d array with 1 on the border and 0 inside.**

In [ ]:
None

**5. Create a 8 x 8 matrix and fill it with a checkerboard pattern.**

In [ ]:
None