#Practical 7
 
Name: Shreyas Dongre   
Roll no: 082        
Division: I                         
Semester: 2nd Semester                                           
Batch: I3                                              
Experiment 7 - To study Arrays and NumPy Arrays in Python.                                  
Date of Experiment: 8/4/2021

#Task 1  
Write a Python program to reverse an array without using an in-built function.


In [ ]:
from array import *
def reverse(a,s,n):
  while s<n:
    a[s],a[n] = a[n],a[s]
    s+=1
    n-=1
  return a


                
a = array('i',[1,2,3,4,5])   
reverse(a,0,4)

array('i', [5, 4, 3, 2, 1])

#Task 2  
Write a Python program to find the frequency of a user given number in an array.(without using an in-built function)


In [ ]:
def freq(a,n,l):
  s=0
  for i in a:
    if n == i:
      s+=1
    
  print(n,'occurs for',s,'times in the array.')  

a = array('i',[1,2,3,1,4,5,1,1,6,7,1,9,5,1])  
l= len(a)
n=int(input('Enter the number '))
freq(a,n,l)




Enter the number 1
1 occurs for 6 times in the array.


#Task 3
Write a Python program to place all negative numbers in the array at the end of the array and  positive numbers in the beginning.


In [ ]:
def arrange(a,l):
  s=0
  for i in range (0,l):
    if (a[i]>0):
      b = a[i]
      a[i]=a[s]
      a[s]=b
      s+=1
  print(a)

a = array('i',[1,-1,-8,-7,7,2,3,46,-6,-8,-9,8,5])  
l= len(a)  
arrange(a,l)

array('i', [1, 7, 2, 3, 46, 8, 5, -1, -6, -8, -9, -8, -7])


#Task 4 
Write a Python program to sort an array in wave form.            
Example :                   
Input: A[] = {2, 4, 6, 8, 10, 20}                  
Output: A[] = {4, 2, 8, 6, 20, 10}


In [ ]:
import numpy as np
def wave(a,l):
  a.sort()
  for i in range (0,l-1,2):
    a[i],a[i+1] = a[i+1],a[i]

a =np.array([2,4,6,8,10,20]) 
l= len(a) 
wave(a,l)

for i in range(0,l):
  print ( a[i] )

4
2
8
6
20
10


#Task 5 
Write a Python program to print a given matrix in spiral form.                   
Example :                    
A = [[1 2 3]                 
         [4 5 6]              
         [7 8 9]]              
Spiral form : 1 2 3 6 9 8 7 4 5    


In [3]:
 def spiral(a,r,c):
   x=0
   y=0
   while (x<r and y<c):
     for i in range(y,c):
       print(a[x][i], end=" ")
     x+=1

     for i in range(x,r):
       print(a[i][c-1],end=" ")
     c-=1
     if (x<r):
       for i in range (c-1,(y-1),-1):
         print(a[r-1][i],end=" ")
       r-=1

     if (y<c):
       for i in range(r-1,x-1,-1):
         print(a[i][y],end=" ")
       y+=1

a = [[1,2,3],[4,5,6],[7,8,9]]
r = 3
c = 3  
spiral(a,r,c)          

             

1 2 3 6 9 8 7 4 5 

#Task 6  
**6.1**	Write a Python program to print ‘k’ smallest element in an unsorted array.               
**6.2** 	Write a Python program to print ‘k’ largest element in an unsorted array.



In [ ]:
#6.1
def small(a,l,k):
  a.sort()
  return a[k-1]

if __name__ == '__main__':
  a=np.array([12,3,5,7,19])  
  l= len(a)
  k=2
small(a,l,k)  

5

In [ ]:
#6.2
def large(b,k):
  b[::-1].sort()
  for i in range (k):
    print(b[i],end=" ")

b = np.array([1,23,12,9,30,2,50])  
k = 2
large(b,k) 

50 30 

#Task 7
Write a Python Program to add two 3x3 Matrices using Nested Loop.


In [ ]:
def add(a,b,r):
  l=len(a)
  m=len(b)

  for i in range (l):
    for j in range (len(a[0])):
      r[i][j] = a[i][j] + b[i][j]
  for k in r:
    print(k)

a=[[1,2,3],[4,5,6],[7,8,9]] 
b=[[9,8,7],[6,5,4],[3,2,1]]       
r=[[0,0,0],[0,0,0],[0,0,0]]
add(a,b,r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


#Task 8
Write a Python Program to multiply two Matrices using Nested Loop.


In [ ]:
def mul (a,b,r):
  for i in range(len(a)):
    for j in range (len(b[0])):
      for k in range (len(b)):
        r[i][j] += a[i][k] * b[k][j]

  for l in r:
    print(l)    

a=[[22,7,3],[4,18,3],[11,4,8]] 
b=[[7,9,2,3],[3,8,6,5],[9,5,3,2]]       
r=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]
mul(a,b,r)


[202, 269, 95, 107]
[109, 195, 125, 108]
[161, 171, 70, 69]


#Task 9
Write a Python Program to Calculate the sum of all columns in a 2D NumPy array             
Example :                            
A = [ [1 2 3]                   
 	    [1 1 1]                 
 	    [1 1 1]]

Column wise Sum: 3 4 5


In [ ]:
def col(a,l,m):
  for i in range (0,l):
    s=0
    for j in range (0,m):
      s+=a[j][i]
    print('Sum of',i+1,'column:',s)

a=[[1,2,3],[1,1,1],[1,1,1]]
l= len(a)
m= len(a[0])     
col(a,l,m) 


Sum of 1 column: 3
Sum of 2 column: 4
Sum of 3 column: 5


#Task 10
Write a Python Program to find Range and Coefficient of range of Array.                 
Range = Max – Min                           
Coefficient of Range = (Max – Min) / (Max + Min)                     
Example :                           
A = [10, 20, 30, 5, 8]                         
Range : 25                    
Coefficient of Range : 0.7142857142857143


In [ ]:
def minimum(a,l):
  res = a[0]
  for i in range (1,l,1):
    res = min(res,a[i])
  return res 

def maximum(a,l):
  res=a[0]
  for i in range(1,l,1):
    res=max(res,a[i])
  return res 

def result(a,l):
  max1 = maximum(a,l)
  min1 = minimum(a,l)
  range= max1-min1
  coef = (max1-min1)/(max1+min1)
  print("Range:",range)
  print("Coefficient of Range:",coef)

if __name__ == '__main__':
  a=[10,20,30,5,8]
  l= len(a)
  result(a,l)  


Range: 25
Coefficient of Range: 0.7142857142857143


#Conclusion
1) Implemented array and Numpy array.         
2) Imported array library and NumPy library for operating on arrays.              
3) Declared NumPy array using np.array().               
4) Used NumPy array slicing to sort.               
5) Used 'for' loop to traverse through the Array.